SHOPS = {
    1: 'Empik',
    2: 'H&M',
    3: 'KappAhl',
    4: 'Mohito',
    5: 'Gino Rossi',
    6: 'Parfois',
    7: 'Super-Pharm',
    8: 'Medicine',
    9: 'Etam',
    10: 'Wojas',
    11: 'Calzedonia',
    12: 'Intimissimi',
    13: 'Reserved',
    14: 'Home&You',
    15: 'McDonalds',
    16: 'Duka',
    17: 'Tchibo',
    18: 'Tezenis',
    19: 'Clarks',
    20: 'Reserved',
    21: 'Chanel',
    22: 'Sephora',
    23: 'Wittchen',
    24: 'Vagabond',
    25: 'Mango',
    26: 'iSpot Apple',
    27: 'Orange',
    28: 'Samsung',
    29: 'Play',
    30: 'Peek&Cloppenburg',
    31: 'Ecco',
    32: 'Rossmann',
    33: 'Deichmann',
    34: 'Smyk',
    35: 'Douglas',
    36: 'Orsay',
    37: 'Triumph',
    38: 'Gatta',
    39: 'W.Kruk',
    40: 'Grycan',
    41: 'CCC',
    42: 'Rylko',
    43: 'Zara',
    44: 'Ochnik',
    45: 'Michael Kors',
    46: 'Hugo Boss',
    47: 'Apart',
    48: 'Converse',
    49: 'Adidas',
    50: 'House',
    51: 'Cropp',
    52: 'RTV Euro AGD',
    53: 'Sizeer',
    54: '4F',
    55: 'Esprit',
    56: 'Swarovski',
    57: 'Pandora',
    58: 'Dior',
    59: 'Tous',
    60: 'Olsen'
}